# Generated by Django 5.0.14 on 2026-08-21 06:55

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_classlevel_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(help_text='Write your notes using the rich text editor', verbose_name='Content')),
                ('description', models.TextField(blank=True, verbose_name='Short Description')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='notes/featured/%Y/%m/%d/', verbose_name='Featured Image')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason why the note was rejected', verbose_name='Rejection Reason')),
                ('rejection_feedback', models.TextField(blank=True, help_text='Detailed feedback for the teacher', verbose_name='Rejection Feedback')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected At')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='academics.chapter', verbose_name='Chapter')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.classlevel', verbose_name='Class Level')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_notes', to=settings.AUTH_USER_MODEL, verbose_name='Rejected By')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='academics.subject', verbose_name='Subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'subject'], name='notes_status_e0a118_idx'), models.Index(fields=['uploaded_by', 'status'], name='notes_uploade_6e3f80_idx'), models.Index(fields=['class_level'], name='notes_class_l_d4c6e0_idx'), models.Index(fields=['rejected_at'], name='notes_rejecte_4fb96d_idx')],
            },
        ),
    ]
