# Generated by Django 5.0.14 on 2026-08-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_oldquestion'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oldquestion',
            table='old_questions',
        ),
    ]
