# Generated by Django 5.0.14 on 2026-08-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternative_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative email addresses'),
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_phones',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative phone numbers'),
        ),
    ]
