# Generated by Django 5.0.14 on 2026-08-05 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otpverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(blank=True, max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'temp_user_data',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Permanent address'),
        ),
        migrations.AddField(
            model_name='user',
            name='class_level',
            field=models.CharField(blank=True, help_text='e.g., Class 12, BSc 1st Year', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='college_school',
            field=models.CharField(blank=True, help_text='College or School name', max_length=255),
        ),
    ]
