# Generated by Django 5.0.14 on 2026-08-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_alternative_emails_user_alternative_phones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='alternative_emails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alternative_phones',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alternative_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative email addresses'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alternative_phones',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative phone numbers'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='alternative_emails',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative email addresses'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='alternative_phones',
            field=models.JSONField(blank=True, default=list, help_text='List of alternative phone numbers'),
        ),
    ]
