# Generated by Django 5.0.14 on 2026-08-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_alternative_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='municipality',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(help_text='college address: e.g., kalanki', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/student'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='Verification',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/teachers'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('not_verified', 'not_verified'), ('verified', 'verified')], default='not_verified', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='school_type',
            field=models.CharField(choices=[('school', 'School'), ('college', 'College'), ('university', 'university')], default='school', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(help_text='Comma separated school names', max_length=100, verbose_name='Subject'),
        ),
    ]
