# Generated by Django 5.0.14 on 2026-08-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_studentprofile_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='Verification',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.JSONField(blank=True, default=list, help_text='List of subjects taught by the teacher', verbose_name='Subjects'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='verification_document',
            field=models.ImageField(blank=True, null=True, upload_to='images/teacher_verification', verbose_name='Verification Document'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='address',
            field=models.CharField(default=2, help_text='e.g., Kalanki, Kathmandu', max_length=200, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('not_verified', 'Not Verified'), ('verified', 'Verified')], default='not_verified', max_length=20, verbose_name='Verification Status'),
        ),
    ]
