# Generated by Django 5.0.14 on 2026-08-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_teacherprofile_verification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='verification_document',
            field=models.FileField(blank=True, null=True, upload_to='images/teacher_verification', verbose_name='Verification Document'),
        ),
    ]
