# Generated by Django 5.0.14 on 2026-08-10 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0008_alter_teacherprofile_verification_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='school_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profiles', to='academics.school', verbose_name='School/College'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classlevel', verbose_name='class_level'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.faculty', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.faculty', verbose_name='faculty'),
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='schools',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='subjects',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='schools',
            field=models.ManyToManyField(blank=True, help_text='Schools/Colleges the student is associated with', related_name='teacher_profiles', to='academics.school', verbose_name='Schools/Colleges'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects taught by the teacher', related_name='teachers', to='academics.subject', verbose_name='Subjects'),
        ),
    ]
