# Generated by Django 5.0.14 on 2026-08-10 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0009_remove_studentprofile_school_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='schools',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='school',
            field=models.ManyToManyField(blank=True, help_text='Schools/Colleges the teacher is associated with', related_name='teacher_profiles', to='academics.school', verbose_name='Schools/Colleges'),
        ),
    ]
