# Generated by Django 5.0.14 on 2026-08-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_teacherprofile_schools_teacherprofile_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='school',
            new_name='schools',
        ),
    ]
