# Generated by Django 5.0.14 on 2026-08-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_school_teacherprofile_schools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='schools',
        ),
    ]
