# Generated by Django 5.0.14 on 2026-08-09 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_teacherprofile_verification_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Class Name')),
                ('level_type', models.CharField(choices=[('SEE', 'SEE (Grade 10)'), ('+2', '+2 (Grade 11-12)'), ('bachelor', 'Bachelor')], max_length=20, verbose_name='Level Type')),
                ('display_order', models.IntegerField(default=0, verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Class Level',
                'verbose_name_plural': 'Class Levels',
                'db_table': 'class_levels',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['level_type'], name='class_level_level_t_115bd8_idx'), models.Index(fields=['display_order'], name='class_level_display_5e4572_idx')],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Faculty Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
                'db_table': 'faculties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='faculties_name_0145b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='School Name')),
                ('address', models.CharField(max_length=255, verbose_name='School Address (Kalanki,Kathmandu)')),
                ('school_type', models.CharField(choices=[('School', 'School'), ('College', 'College'), ('University', 'University')], default='School', max_length=20, verbose_name='School Type')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'schools',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.classlevel', verbose_name='Class Level')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Chapter Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='academics.subject', verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'chapters',
                'ordering': ['subject', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schools', to='academics.school', verbose_name='School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_schools', to='accounts.teacherprofile', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Teacher School',
                'verbose_name_plural': 'Teacher Schools',
                'db_table': 'teacher_schools',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['name'], name='schools_name_2838ce_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['school_type'], name='schools_school__eef8c2_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['faculty', 'class_level'], name='subjects_faculty_0f0221_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name'], name='subjects_name_ff98e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('faculty', 'class_level', 'name')},
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['subject'], name='chapters_subject_5fe30d_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['name'], name='chapters_name_151e12_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherschool',
            index=models.Index(fields=['teacher', 'school'], name='teacher_sch_teacher_3003fc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherschool',
            unique_together={('teacher', 'school')},
        ),
    ]
