# Generated by Django 5.0.14 on 2026-08-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlevel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Class Name'),
        ),
    ]
